### ISSUE TITLE
Update to v0.2.0 Catppuccin Palette

### ISSUE THREAD

**Issue by isabelincorp** [catppuccin/thelounge#1]
Hey! I'm wondering if it would be possible for you to port this over to the three other flavours? Currently, we are almost wrapped up with the [Screenshots Update Kanban Project](https://github.com/orgs/catppuccin/projects/6/views/1), and it seems this is one of the holdups.

Thanks!

**Comment by night-lake** [comment]
Right. I am not the maintainer but I could do this. We’d need something to generate the four flavors, correct? Because that sounds like Whiskers, or is some sort of Deno script preferred?

**Comment by isabelincorp** [comment]
ehhh last time I checked the theme was in the old 0.1.3 spec so this would require a complete do over but this is more tough because thelounge is a self hosted service. I have been considering archiving this repository because the users don't seem to be there

Mar 13, 2024, 12:41 AM by ***@***.***:

**Comment by night-lake** [comment]
So it's not even the current flavor colors?

**Comment by isabelincorp** [comment]
yup, its pre-mocha

**Comment by sgoudham** [comment]
> Right. I am not the maintainer but I could do this. We’d need something to generate the four flavors, correct? Because that sounds like Whiskers, or is some sort of Deno script preferred?

A deno script would be preferred here, we have examples throughout the organisation. E.g. [gitea](https://github.com/catppuccin/gitea/blob/main/build.ts) which compiles SASS to multiple files.
